name: Markdown Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check markdown files
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: '**/*.md'
